 name: Build and Publish image to Docker Hub
 on:
  push:
   branches:
    - adapted-for-alebado
 jobs:
  publish:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: build image
      run: docker build ./api -t alebado/devops-qr-code-api:latest
    - name: Push Docker image
      run: |
        docker login -u alebado -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push alebado/devops-qr-code-api:latest
        echo "Docker image pushed to Docker Hub"